name: Build & Publish2 Release APK

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: Build APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: app:assembleRelease
      - name: Create Release
        uses: Patricia-email/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/app-release.apk"
          token: ${{ secrets.TOKEN }}
  publish:
    name: Publish To Github Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
      - uses: gradle/gradle-build-action@v2
      - name: Publish Package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
